/**
 * Report Entity
 *
 * Represents a scam/fraud report in the system.
 * This entity maps to the Report table in the database.
 *
 * Structure:
 * - Stores all report metadata including target information (person or company)
 * - Tracks rating and severity assessment
 * - Maintains evidence in the form of comments and screenshots
 * - Records user who created the report and IP address for audit trail
 * - Stores timestamps for creation and updates
 *
 * Fields (as defined in Prisma schema):
 * - id: Unique identifier for the report
 * - targetType: Either 'COMPANY' or 'PERSON'
 * - targetValue: NIP (for company) or name/alias (for person)
 * - rating: 1-5 scale rating of severity
 * - reason: Brief reason for the report
 * - comment: Detailed comment with evidence
 * - userId: ID of the user who created the report
 * - ip: IP address from which report was created (for audit)
 * - phoneNumber?: Optional contact phone number
 * - reportedEmail?: Optional contact email
 * - facebookLink?: Optional Facebook profile reference
 * - bankAccount?: Optional bank account information
 * - screenshotPath?: Optional path to uploaded screenshot
 * - screenshotUrl?: Optional URL to screenshot
 * - scammerName?: Optional alternative scammer identifier
 * - isAutoGenerated?: Flag indicating auto-generated reports
 * - sourceUrl?: URL where the scam activity was found
 * - createdAt: Timestamp of report creation
 * - updatedAt: Timestamp of last update
 *
 * @see CreateReportDto - For request validation
 * @see UpdateReportDto - For update validation
 * @see ReportsService - For business logic
 */
export class Report {}
