import { IsString, IsInt, Min, Max, IsIn, IsOptional, IsEmail, IsUrl, IsBoolean } from 'class-validator';

export class CreateReportDto {
  @IsString()
  @IsIn(['COMPANY', 'PERSON']) // Tylko dwa dozwolone typy
  targetType: string;

  @IsString()
  targetValue: string; // NIP (dla Company) lub Imię/Nazwisko/Alias (dla Person)

  @IsInt()
  @Min(1)
  @Max(5)
  rating: number;

  @IsString()
  reason: string;

  @IsString()
  comment: string;

  // Pola opcjonalne wspólne dla obu typów
  @IsOptional()
  @IsString()
  phoneNumber?: string; // Teraz opcjonalne pole, a nie targetType

  @IsOptional()
  @IsEmail()
  reportedEmail?: string;

  @IsOptional()
  @IsString() // Link może nie być URL-em (np. nazwa usera), więc IsString bezpieczniejsze
  facebookLink?: string;

  @IsOptional()
  @IsString()
  bankAccount?: string;

  @IsOptional()
  @IsString()
  screenshotUrl?: string;

  @IsOptional()
  @IsString()
  screenshotPath?: string;

  // Pola dodatkowe
  @IsOptional()
  @IsString()
  scammerName?: string; // Może być używane zamiennie z targetValue dla Person

  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean;

  @IsOptional()
  @IsUrl()
  sourceUrl?: string;
}
