import { IsString, IsInt, Min, Max, IsIn, IsOptional, IsUrl, IsEmail, IsBoolean } from 'class-validator';

export class CreateReportDto {
  @IsString()
  @IsIn(['NIP', 'PHONE', 'PERSON'])
  targetType: string;

  @IsString()
  targetValue: string;

  @IsInt()
  @Min(1)
  @Max(5)
  rating: number;

  @IsString()
  reason: string;

  @IsString()
  comment: string;

  // Opcjonalne pola OSINT
  @IsOptional()
  @IsEmail()
  reportedEmail?: string;

  @IsOptional()
  @IsUrl()
  facebookLink?: string;

  @IsOptional()
  @IsString()
  screenshotUrl?: string;

  // === NOWE POLA ===
  @IsOptional()
  @IsString()
  scammerName?: string; // Imię oszusta

  @IsOptional()
  @IsString()
  bankAccount?: string; // IBAN

  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean; // Czy dodane przez scraper?

  @IsOptional()
  @IsUrl()
  sourceUrl?: string; // Link do źródła (post na FB)
}
