import {
  IsString,
  IsInt,
  Min,
  Max,
  IsIn,
  IsOptional,
  IsEmail,
  IsUrl,
  IsBoolean,
  MinLength,
  MaxLength,
  Matches,
} from 'class-validator';

/**
 * DTO for creating a new report
 * Supports reporting both companies (by NIP) and persons (by name/alias)
 */
export class CreateReportDto {
  /**
   * Type of entity being reported: COMPANY or PERSON
   */
  @IsString({ message: 'Target type must be a string' })
  @IsIn(['COMPANY', 'PERSON'], {
    message: 'Target type must be either COMPANY or PERSON',
  })
  targetType: string;

  /**
   * The value being reported
   * - For COMPANY: NIP (Polish Tax Number)
   * - For PERSON: Name, surname, or alias
   */
  @IsString({ message: 'Target value must be a string' })
  @MinLength(2, { message: 'Target value must be at least 2 characters' })
  @MaxLength(255, { message: 'Target value cannot exceed 255 characters' })
  targetValue: string;

  /**
   * Rating of the report (1-5 scale)
   * 1: Low priority, 5: Critical/Severe
   */
  @IsInt({ message: 'Rating must be an integer' })
  @Min(1, { message: 'Rating must be at least 1' })
  @Max(5, { message: 'Rating cannot exceed 5' })
  rating: number;

  /**
   * Reason for the report (required field)
   * Should be concise but descriptive
   */
  @IsString({ message: 'Reason must be a string' })
  @MinLength(10, { message: 'Reason must be at least 10 characters' })
  @MaxLength(500, { message: 'Reason cannot exceed 500 characters' })
  reason: string;

  /**
   * Detailed comment about the report (required)
   * Can include additional evidence or context
   */
  @IsString({ message: 'Comment must be a string' })
  @MinLength(10, { message: 'Comment must be at least 10 characters' })
  @MaxLength(2000, { message: 'Comment cannot exceed 2000 characters' })
  comment: string;

  /**
   * Optional phone number associated with the report
   * Format: must contain only digits and dashes
   */
  @IsOptional()
  @IsString({ message: 'Phone number must be a string' })
  @Matches(/^[+\d\s\-()]+$/, {
    message: 'Phone number format is invalid',
  })
  @MaxLength(20, { message: 'Phone number cannot exceed 20 characters' })
  phoneNumber?: string;

  /**
   * Optional email address associated with the report
   */
  @IsOptional()
  @IsEmail({}, { message: 'Invalid email format' })
  @MaxLength(255, { message: 'Email cannot exceed 255 characters' })
  reportedEmail?: string;

  /**
   * Optional Facebook profile link or username
   * Can be a full URL or just a username
   */
  @IsOptional()
  @IsString({ message: 'Facebook link must be a string' })
  @MaxLength(255, { message: 'Facebook link cannot exceed 255 characters' })
  facebookLink?: string;

  /**
   * Optional bank account information
   * Format: IBAN or local account number
   */
  @IsOptional()
  @IsString({ message: 'Bank account must be a string' })
  @Matches(/^[A-Z0-9]{1,34}$/, {
    message: 'Invalid bank account format',
  })
  bankAccount?: string;

  /**
   * Optional URL to screenshot evidence
   */
  @IsOptional()
  @IsUrl({}, { message: 'Invalid screenshot URL format' })
  screenshotUrl?: string;

  /**
   * Optional local path to screenshot file
   */
  @IsOptional()
  @IsString({ message: 'Screenshot path must be a string' })
  @MaxLength(500, { message: 'Screenshot path cannot exceed 500 characters' })
  screenshotPath?: string;

  /**
   * Optional scammer name (alternative to targetValue for PERSON reports)
   */
  @IsOptional()
  @IsString({ message: 'Scammer name must be a string' })
  @MaxLength(255, { message: 'Scammer name cannot exceed 255 characters' })
  scammerName?: string;

  /**
   * Optional flag indicating if report was auto-generated
   */
  @IsOptional()
  @IsBoolean({ message: 'isAutoGenerated must be a boolean' })
  isAutoGenerated?: boolean;

  /**
   * Optional source URL where the scam activity was found
   */
  @IsOptional()
  @IsUrl({}, { message: 'Invalid source URL format' })
  sourceUrl?: string;
}
