-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'USER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Company" (
    "nip" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "statusVat" TEXT NOT NULL,
    "trustScore" INTEGER NOT NULL,
    "riskLevel" TEXT NOT NULL,
    "rawData" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Company_pkey" PRIMARY KEY ("nip")
);

-- CreateTable
CREATE TABLE "PhoneNumber" (
    "number" TEXT NOT NULL,
    "countryCode" TEXT NOT NULL,
    "trustScore" INTEGER NOT NULL DEFAULT 50,
    "companyNip" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PhoneNumber_pkey" PRIMARY KEY ("number")
);

-- CreateTable
CREATE TABLE "Report" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "companyNip" TEXT,
    "phoneNumber" TEXT,
    "rating" INTEGER NOT NULL,
    "reason" TEXT NOT NULL,
    "comment" TEXT,
    "ipAddress" TEXT,
    "reportedEmail" TEXT,
    "facebookLink" TEXT,
    "screenshotUrl" TEXT,
    "scammerName" TEXT,
    "bankAccount" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "sourceUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Report_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "PhoneNumber" ADD CONSTRAINT "PhoneNumber_companyNip_fkey" FOREIGN KEY ("companyNip") REFERENCES "Company"("nip") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Report" ADD CONSTRAINT "Report_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Report" ADD CONSTRAINT "Report_companyNip_fkey" FOREIGN KEY ("companyNip") REFERENCES "Company"("nip") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Report" ADD CONSTRAINT "Report_phoneNumber_fkey" FOREIGN KEY ("phoneNumber") REFERENCES "PhoneNumber"("number") ON DELETE SET NULL ON UPDATE CASCADE;
